wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.7.0
      5: 0.10.27
      8:
      - 5
adj_num:
  desc: null
  value: 4
approx_factor:
  desc: null
  value: 0.007
batch_size:
  desc: null
  value: 12
checkepoch:
  desc: null
  value: 590
cls_threshold:
  desc: null
  value: 0.875
cuda:
  desc: null
  value: false
dataset:
  desc: null
  value: TD500
device:
  desc: null
  value: cpu
dis_threshold:
  desc: null
  value: 0.3
display_freq:
  desc: null
  value: 10
epochs:
  desc: null
  value: 200
exp_name:
  desc: null
  value: Totaltext
gamma:
  desc: null
  value: 0.1
global_checkepoch:
  desc: null
  value: -1
global_dataset:
  desc: null
  value: TD500
global_epochs:
  desc: null
  value: 200
global_gpu:
  desc: null
  value:
  - 0
global_log_dir:
  desc: null
  value: log_dir
global_output_idr:
  desc: null
  value: output
global_pretrain:
  desc: null
  value: true
global_pretrain_model:
  desc: null
  value: ./model/TD500/TextBPN_resnet50_680.pth
global_print_freq:
  desc: null
  value: 2
global_save_freq:
  desc: null
  value: 10
global_save_path:
  desc: null
  value: ./checkpoints/
global_use_gpu:
  desc: null
  value: false
global_val_freq:
  desc: null
  value: 1
global_vis_dir:
  desc: null
  value: vis_dir
gpu:
  desc: null
  value:
  - 0
grad_clip:
  desc: null
  value: 0
input_size:
  desc: null
  value: 640
log_dir:
  desc: null
  value: log_dir
log_freq:
  desc: null
  value: 10000
loss:
  desc: null
  value: CrossEntropyLoss
lr:
  desc: null
  value: 0.001
lr_adjust:
  desc: null
  value: fix
max_annotation:
  desc: null
  value: 64
max_epoch:
  desc: null
  value: 200
max_points:
  desc: null
  value: 20
means:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
mgpu:
  desc: null
  value: false
momentum:
  desc: null
  value: 0.9
net:
  desc: null
  value: resnet50
num_points:
  desc: null
  value: 20
num_workers:
  desc: null
  value: 1
optim:
  desc: null
  value: Adam
output_dir:
  desc: null
  value: output
output_idr:
  desc: null
  value: output
pretrain:
  desc: null
  value: ./model/TD500/TextBPN_resnet50_680.pth
pretrain_model:
  desc: null
  value: ./model/TD500/TextBPN_resnet50_680.pth
print_freq:
  desc: null
  value: 2
rescale:
  desc: null
  value: 255.0
save_dir:
  desc: null
  value: checkpoints
save_freq:
  desc: null
  value: 5
save_path:
  desc: null
  value: ./checkpoints/
scale:
  desc: null
  value: 1
start_epoch:
  desc: null
  value: 0
stds:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
stepvalues:
  desc: null
  value: []
test_size:
  desc: null
  value:
  - 640
  - 1024
train_adj_num:
  desc: null
  value: 4
train_approx_factor:
  desc: null
  value: 0.007
train_batch_size:
  desc: null
  value: 12
train_cls_threshold:
  desc: null
  value: 0.8
train_data_root:
  desc: null
  value: data/TD500
train_dis_threshold:
  desc: null
  value: 0.3
train_gamma:
  desc: null
  value: 0.1
train_grad_clip:
  desc: null
  value: 0
train_input_size:
  desc: null
  value: 512
train_lr:
  desc: null
  value: 0.0001
train_max_annotation:
  desc: null
  value: 64
train_max_points:
  desc: null
  value: 20
train_num_points:
  desc: null
  value: 20
train_num_workers:
  desc: null
  value: 0
train_rgb_mean:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
train_rgb_std:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
train_scale:
  desc: null
  value: 1
train_shuffle:
  desc: null
  value: true
train_step_size:
  desc: null
  value: 20
train_use_hard:
  desc: null
  value: true
use_gpu:
  desc: null
  value: false
use_hard:
  desc: null
  value: true
val_batch_size:
  desc: null
  value: 1
val_data_root:
  desc: null
  value: data/TD500
val_freq:
  desc: null
  value: 1
val_input_size:
  desc: null
  value: 512
val_num_workers:
  desc: null
  value: 1
val_rgb_mean:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
val_rgb_std:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
val_shuffle:
  desc: null
  value: false
vis_dir:
  desc: null
  value: vis_dir
viz:
  desc: null
  value: false
viz_freq:
  desc: null
  value: 50
wandb_flag:
  desc: null
  value: true
wandb_name:
  desc: null
  value: ./TD500
wandb_project:
  desc: null
  value: TextBPN
weight_decay:
  desc: null
  value: 0.0
